# Generated by Django 4.0.3 on 2022-03-27 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Campeonato')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('data', models.DateTimeField(verbose_name='Data e hora do jogo')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Jogo finalizado?')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, verbose_name='Nome do Time')),
                ('gol', models.PositiveIntegerField(verbose_name='Gol')),
            ],
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogo', to='core.jogo', verbose_name='Jogo')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.time', verbose_name='Time')),
            ],
        ),
    ]
