# Generated by Django 4.0.3 on 2022-03-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='gol',
            field=models.PositiveIntegerField(default=1, verbose_name='Gols'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='time',
            field=models.CharField(max_length=10, verbose_name='Time'),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
